### ISSUE TITLE
App doesn't run on iPhone 5 and lower devices

### ISSUE THREAD

**Issue by michieriffic** [WWDCScholars/WWDCScholars-iOS#10]
App seems to be having errors when running on iPhone 5 and lower devices

![screen shot 2016-06-03 at 11 14 28 am](https://cloud.githubusercontent.com/assets/12575688/15773706/0d1b1f56-29ab-11e6-82e1-d913ef4b4793.png)

**Comment by Andrew-Walker** [comment]
I managed to get it to run on both iPhone 4S and 5S with no problems, but then encountered the same issue on a second attempt.

**Comment by michieriffic** [comment]
@Andrew-Walker you're almost there! 👍
