### ISSUE TITLE
To add ability to submit post directly from the iOS app instead of URL 

### ISSUE THREAD

**Issue by michieriffic** [WWDCScholars/WWDCScholars-iOS#12]
@matthijs2704 @Sam0711er @Andrew-Walker 

I would like to try to add a WYSIWG editor directly to our app to be able to submit post. Are you cool with that or you guys prefer people to submit using the SafariViewController?

**Comment by matthijs2704** [comment]
We will not do this in 1.x release of this year. We just don't have time for that. That's why I will close this issue for now.
