### ISSUE TITLE
make ActivityQueryItem & ActivityTimelineFilter indexable?

### ISSUE THREAD

**Issue by thisIsTheFoxe** [WWDCScholars/WWDCScholars-iOS#128]
`"Type is not marked indexable"` - `error` in ActivityViewControllerProxy.swift: `loadActivityTimelineFilters()`
`"Type is not marked indexable"` - `error` in ActivityViewControllerProxy.swift: `loadActivityQueryItems()`

Afaik there has to be at least one indexable attribute in order to perform a query on a "Type".

**Comment by Sam0711er** [comment]
Activity works now
