### ISSUE TITLE
Will the chat feature be in the next version?

### ISSUE THREAD

**Issue by DrBeta** [WWDCScholars/WWDCScholars-iOS#129]
I downloaded the old app and found the chat feature exciting. I know there is a discord, but is the chat feature going to be in the next version?

**Comment by thisIsTheFoxe** [comment]
If you look at the current [develop](https://github.com/WWDCScholars/iOS-app) branch you can see that we are working on a twitter implementation and I feel like that would actually be better and more convenient than an actual chat.. 
However, as #111 suggests this might change in the future :)

**Comment by Sam0711er** [comment]
I can confirm a chat-like feature like in the 2016 version is not what the activity tab might evolve in to, however we're always grateful for cool ideas ;)
