### ISSUE TITLE
App Crashes when you tap a profile picture

### ISSUE THREAD

**Issue by greggmojica** [WWDCScholars/WWDCScholars-iOS#13]
On the Scholar Detail Page, when you tap a profile picture the app crashes.

**Comment by Sam0711er** [comment]
Can't reproduce the issue here. Which Scholar?

**Comment by greggmojica** [comment]
Crashes on every scholar (when you tap their picture to enlarge it).  Tested this on iPhone 6. Doesn't seem to appear any other device.

**Comment by matthijs2704** [comment]
Works for me on iPhone 6

**Comment by matthijs2704** [comment]
Please add the crashlog in the issue next time

**Comment by matthijs2704** [comment]
Closing old issue, no crashlog attached. Feel free to reopen with a crashlog :)
