### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by ghost** [WWDCScholars/WWDCScholars-iOS#135]
![E3D49D49-1115-4FB4-A1B1-1C0FB62B8DFE](https://user-images.githubusercontent.com/40307305/58990224-d5604100-87bb-11e9-82f8-a8060fea155c.jpeg)
![D1101680-8661-44FA-B9CC-6A8A5D7F5A67](https://user-images.githubusercontent.com/40307305/58990353-19ebdc80-87bc-11e9-829d-85f73a55f112.gif)

**Comment by matthijs2704** [comment]
Hi nathfreder,
Hmm that is odd! Let's try to figure out where the crash comes from :)

Are you logged in to iCloud?

**Comment by ghost** [comment]
Yup @matthijs2704

**Comment by matthijs2704** [comment]
Could you try again for me please? I want to know if the issue still happens.

**Comment by ghost** [comment]
It's working!

**Comment by matthijs2704** [comment]
Awesome! :)
I suspect there was something wrong in the database or there was some outage.

Have a nice day!
