### ISSUE TITLE
App crashes when trying to edit profile

### ISSUE THREAD

**Issue by clasqui** [WWDCScholars/WWDCScholars-iOS#15]
There's a bug that causes an app crash when I try to edit my profile.  It happens indistinctly of the way I try to get into the EditProfileTableViewController: Using the profile icon, tapping the edit button when in my profile or through the home screen quick-action.
The error stack: 

```
#1  0x000000010017b860 in URLRequest(Method, URLStringConvertible, headers : [String : String]?) -> NSMutableURLRequest at /Volumes/Transcend/XCode/WWDCScholars-iOS/WWDCScholars/Source/Alamofire.swift:92
fatal error: unexpectedly found nil while unwrapping an Optional value

```

To add more information, my profile was created for last year's scholars app, and I didn't create the account so I logged in using the default password.

**Comment by clasqui** [comment]
# Update: New Info

As I told you on the slack channel, the bug is related to the screenshots.  When I try to edit my profile, the debugger throws the known error `fatal error: unexpectedly found nil while unwrapping an Optional value`.  If we inspect the code, we can see the conflicting line is: 

```
let mutableURLRequest = NSMutableURLRequest(URL: NSURL(string: URLString.URLString)!)
```

The `URLString`.variable  here is my first screenshot address, which is _https://wwdcscholars.s3.amazonaws.com/scholarImages/2015_MarcClascàRamírez_screenshotTwo.png_.  I tried it in a playground and the method NSURL(string: String)? returns nil with this address, and I guess with every address containing special characters (note the à and the í).  So when we force unwrap the optional that this method returns, the app crashes.

What I didn't get to understand is why in the Details View the screenshots simply don't load (you can see the _no screenshots available_ label) but in the Edit Details View it crashes.

**Comment by matthijs2704** [comment]
I know the fix
