### ISSUE TITLE
Add Intro

### ISSUE THREAD

**Issue by Sam0711er** [WWDCScholars/WWDCScholars-iOS#36]

**Comment by matthijs2704** [comment]
No

**Comment by Sam0711er** [comment]
Yes, we agreed on that. [URL](http://prntscr.com/f5fppi)

**Comment by matthijs2704** [comment]
Nope, we've changed that later. We want people to immediately experience the app, without having to skip through pages with information which is on the App Store page anyways. Also there is no login screen anymore at the end.

**Comment by Sam0711er** [comment]
Intro with ability to skip will be added.
