### ISSUE TITLE
Chat seems to be crashing when tab bar is clicked

### ISSUE THREAD

**Issue by michieriffic** [WWDCScholars/WWDCScholars-iOS#9]
This is the error I am having.

`2016-06-03 11:11:51.905 Scholars[7625:1338802] *** Assertion failure in -[Scholars.ChatViewController viewWillAppear:], /WWDCScholarsIOSLatest/JSQMessagesViewController/Controllers/JSQMessagesViewController.m:277
2016-06-03 11:11:51.917 Scholars[7625:1338802] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: self.senderId != nil'
*** First throw call stack:
(
    0   CoreFoundation                      0x00000001030a1d85 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000102a44deb objc_exception_throw + 48
    2   CoreFoundation                      0x00000001030a1bea +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x000000010268ed5a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    4   Scholars                            0x000000010034f386 -[JSQMessagesViewController viewWillAppear:] + 342
    5   UIKit                               0x00000001048482bd -[UIViewController _setViewAppearState:isAnimating:] + 710
    6   UIKit                               0x0000000104848958 -[UIViewController __viewWillAppear:] + 149
    7   UIKit                               0x0000000104887c83 -[UINavigationController _startTransition:fromViewController:toViewController:] + 781
    8   UIKit                               0x0000000104888c4d -[UINavigationController _startDeferredTransitionIfNeeded:] + 890
    9   UIKit                               0x0000000104889d0b -[UINavigationController __viewWillLayoutSubviews] + 57
    10  UIKit                               0x0000000104a38503 -[UILayoutContainerView layoutSubviews] + 248
    11  UIKit                               0x0000000104762980 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 703
    12  QuartzCore                          0x0000000100e7ac00 -[CALayer layoutSublayers] + 146
    13  QuartzCore                          0x0000000100e6f08e _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
    14  QuartzCore                          0x0000000100e6ef0c _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
    15  QuartzCore                          0x0000000100e633c9 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 277
    16  QuartzCore                          0x0000000100e91086 _ZN2CA11Transaction6commitEv + 486
    17  UIKit                               0x00000001046a272e _UIApplicationHandleEventQueue + 7135
    18  CoreFoundation                      0x0000000102fc7301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    19  CoreFoundation                      0x0000000102fbd22c __CFRunLoopDoSources0 + 556
    20  CoreFoundation                      0x0000000102fbc6e3 __CFRunLoopRun + 867
    21  CoreFoundation                      0x0000000102fbc0f8 CFRunLoopRunSpecific + 488
    22  GraphicsServices                    0x0000000106cd1ad2 GSEventRunModal + 161
    23  UIKit                               0x00000001046a7f09 UIApplicationMain + 171
    24  Scholars                            0x00000001004216a2 main + 114
    25  libdyld.dylib                       0x000000010692892d start + 1
    26  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)`

**Comment by matthijs2704** [comment]
Known issue. Log in first, then press chat

**Comment by michieriffic** [comment]
@matthijs2704 log in using the password on the form?

**Comment by matthijs2704** [comment]
Yes

**Comment by matthijs2704** [comment]
And scholars should be loaded

**Comment by michieriffic** [comment]
Then i suggest UX flow should be change to that if someone presses the chat tab bar and
If he or she isn't login then login VC should pop up
Else move forward to the chatroom 

For the scholars should be loaded, is there a way we can disable chat tab bar if scholars are not loaded yet? :)

**Comment by matthijs2704** [comment]
@michieriffic we already decided how we were gonna do that. Chat screen will still show but I just didn't have time yet to implement it. And no we're not going to disable the chat button if scholars are not loaded. Same as log in. You'll see hahaha

**Comment by michieriffic** [comment]
@matthijs2704 i'll wait, surprise me. LOL!!!
